# Generated by Django 5.2.15 on 2026-09-25 06:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'db_table': 'workflows',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('sequence', models.FloatField(default=65535)),
                ('group', models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('triage', 'Triage')], default='backlog', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Workflow State',
                'verbose_name_plural': 'Workflow States',
                'db_table': 'workflow_states',
                'ordering': ('sequence',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Workflow Transition',
                'verbose_name_plural': 'Workflow Transitions',
                'db_table': 'workflow_transitions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='state',
            name='state_unique_name_project_when_deleted_at_null',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='state',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='db.issuetype'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='issuetype',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_types', to='db.workflow'),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workflowstate',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='db.workflow'),
        ),
        migrations.AddField(
            model_name='state',
            name='workflow_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_mirrors', to='db.workflowstate'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('type__isnull', True)), fields=('project', 'name'), name='state_unique_legacy_name_project_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('type__isnull', False)), fields=('project', 'type', 'name'), name='state_unique_name_project_type_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('workflow_state__isnull', False)), fields=('project', 'workflow_state'), name='state_unique_project_workflow_state_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(condition=models.Q(('default', True), ('deleted_at__isnull', True), ('type__isnull', False)), fields=('project', 'type'), name='state_unique_default_project_type_when_deleted_at_null'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='from_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='db.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='db.workflowstate'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workflowtransition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='db.workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'name'), name='workflow_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow', 'name'), name='workflow_state_unique_name_workflow_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow', 'slug'), name='workflow_state_unique_slug_workflow_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_default', True)), fields=('workflow',), name='workflow_state_unique_default_workflow_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workflow', 'from_state', 'to_state'), name='workflow_transition_unique_pair_when_deleted_at_null'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.CheckConstraint(condition=models.Q(('from_state', models.F('to_state')), _negated=True), name='workflow_transition_from_state_differs_from_to_state'),
        ),
    ]
