# Generated by Django 5.2.15 on 2026-09-25 07:03

from django.db import migrations
from django.utils.text import slugify


WORKFLOW_SEEDS = [
    {
        "type": "Incident",
        "workflow": "Incident Workflow",
        "states": [
            ("New", "backlog", True),
            ("In Progress", "started", False),
            ("On Hold", "started", False),
            ("Resolved", "completed", False),
            ("Closed", "completed", False),
        ],
        "transitions": [
            ("New", "In Progress"),
            ("In Progress", "On Hold"),
            ("In Progress", "Resolved"),
            ("On Hold", "In Progress"),
            ("Resolved", "Closed"),
            ("Resolved", "In Progress"),
        ],
    },
    {
        "type": "Problem",
        "workflow": "Problem Workflow",
        "states": [
            ("New", "backlog", True),
            ("Investigating", "started", False),
            ("Known Error", "started", False),
            ("Resolved", "completed", False),
            ("Closed", "completed", False),
        ],
        "transitions": [
            ("New", "Investigating"),
            ("Investigating", "Known Error"),
            ("Investigating", "Resolved"),
            ("Known Error", "Resolved"),
            ("Known Error", "Investigating"),
            ("Resolved", "Closed"),
            ("Resolved", "Investigating"),
        ],
    },
    {
        "type": "Change",
        "workflow": "Change Workflow",
        "states": [
            ("New", "backlog", True),
            ("Assessment", "started", False),
            ("Approval", "started", False),
            ("Implementation", "started", False),
            ("Review", "started", False),
            ("Closed", "completed", False),
        ],
        "transitions": [
            ("New", "Assessment"),
            ("Assessment", "Approval"),
            ("Assessment", "Closed"),
            ("Approval", "Implementation"),
            ("Approval", "Assessment"),
            ("Implementation", "Review"),
            ("Review", "Closed"),
            ("Review", "Implementation"),
        ],
    },
    {
        "type": "Improvement",
        "workflow": "Improvement Workflow",
        "states": [
            ("New", "backlog", True),
            ("In Progress", "started", False),
            ("Done", "completed", False),
        ],
        "transitions": [
            ("New", "In Progress"),
            ("In Progress", "Done"),
            ("In Progress", "New"),
            ("Done", "In Progress"),
        ],
    },
]

GROUP_COLORS = {
    "backlog": "#60646C",
    "unstarted": "#60646C",
    "started": "#F59E0B",
    "completed": "#46A758",
    "cancelled": "#9AA4BC",
}


SEED_EXTERNAL_SOURCE = "plane-default-itsm"


def _seed_key(seed):
    return slugify(seed["type"])


def _workflow_external_id(seed):
    return f"workflow:{_seed_key(seed)}"


def _issue_type_external_id(seed):
    return f"issue-type:{_seed_key(seed)}"


def _workflow_state_external_id(seed, state_name):
    return f"workflow-state:{_seed_key(seed)}:{slugify(state_name)}"


def _active_marker_rows(model, filters):
    return list(
        model.objects.filter(
            deleted_at__isnull=True,
            external_source=SEED_EXTERNAL_SOURCE,
            **filters,
        )
    )


def _conflict(workspace, seed, detail):
    raise RuntimeError(
        f"Cannot seed {seed['workflow']!r} for workspace "
        f"{workspace.name!r} ({workspace.id}): {detail}"
    )


def _get_workflow(Workflow, workspace, seed):
    workflow_external_id = _workflow_external_id(seed)
    marked_workflows = _active_marker_rows(
        Workflow,
        {
            "workspace_id": workspace.id,
            "external_id": workflow_external_id,
        },
    )
    named_workflows = list(
        Workflow.objects.filter(
            workspace_id=workspace.id,
            name=seed["workflow"],
            deleted_at__isnull=True,
        )
    )
    if len(marked_workflows) > 1:
        _conflict(workspace, seed, "multiple active workflows have the seed ownership marker")
    if len(named_workflows) > 1:
        _conflict(workspace, seed, "multiple active workflows have the seed workflow name")

    if marked_workflows:
        workflow = marked_workflows[0]
        if named_workflows and named_workflows[0].id != workflow.id:
            _conflict(
                workspace,
                seed,
                "a different active workflow already uses the seed workflow name",
            )
        return workflow

    if named_workflows:
        workflow = named_workflows[0]
        _conflict(
            workspace,
            seed,
            f"active workflow {seed['workflow']!r} exists without the exact seed marker "
            f"(external ownership: {workflow.external_source!r}, {workflow.external_id!r}); "
            "refusing to adopt or merge it",
        )

    return Workflow.objects.create(
        workspace_id=workspace.id,
        name=seed["workflow"],
        is_active=True,
        external_source=SEED_EXTERNAL_SOURCE,
        external_id=workflow_external_id,
    )


def _get_workflow_state(WorkflowState, workspace, seed, workflow, state_name, group, is_default, index):
    state_external_id = _workflow_state_external_id(seed, state_name)
    marked_states = _active_marker_rows(
        WorkflowState,
        {
            "workflow__workspace_id": workspace.id,
            "external_id": state_external_id,
        },
    )
    named_states = list(
        WorkflowState.objects.filter(
            workflow_id=workflow.id,
            name=state_name,
            deleted_at__isnull=True,
        )
    )
    if len(marked_states) > 1:
        _conflict(workspace, seed, f"multiple active states have marker {state_external_id!r}")
    if len(named_states) > 1:
        _conflict(workspace, seed, f"multiple active states have name {state_name!r}")

    if marked_states:
        state = marked_states[0]
        if named_states and named_states[0].id != state.id:
            _conflict(
                workspace,
                seed,
                f"a different active state already uses the seed state name {state_name!r}",
            )
        if state.workflow_id != workflow.id:
            _conflict(
                workspace,
                seed,
                f"state marker {state_external_id!r} belongs to a different workflow",
            )
        return state

    if named_states:
        state = named_states[0]
        _conflict(
            workspace,
            seed,
            f"active workflow state {state_name!r} exists without the exact seed marker "
            f"(external ownership: {state.external_source!r}, {state.external_id!r}); "
            "refusing to adopt or merge it",
        )

    return WorkflowState.objects.create(
        workflow_id=workflow.id,
        name=state_name,
        group=group,
        color=GROUP_COLORS[group],
        slug=slugify(state_name),
        sequence=(index + 1) * 15000,
        is_default=is_default,
        external_source=SEED_EXTERNAL_SOURCE,
        external_id=state_external_id,
    )


def _get_issue_type(IssueType, workspace, seed, workflow):
    issue_type_external_id = _issue_type_external_id(seed)
    named_types = list(
        IssueType.objects.filter(
            workspace_id=workspace.id,
            name=seed["type"],
            deleted_at__isnull=True,
        )
    )
    if len(named_types) > 1:
        _conflict(
            workspace,
            seed,
            f"multiple active issue types have name {seed['type']!r}; refusing to choose one",
        )

    marked_types = _active_marker_rows(
        IssueType,
        {
            "workspace_id": workspace.id,
            "external_id": issue_type_external_id,
        },
    )
    if len(marked_types) > 1:
        _conflict(workspace, seed, "multiple active issue types have the seed ownership marker")

    if marked_types:
        issue_type = marked_types[0]
        if named_types and named_types[0].id != issue_type.id:
            _conflict(
                workspace,
                seed,
                "a different active issue type already uses the seed type name",
            )
        if issue_type.workflow_id is None:
            _conflict(
                workspace,
                seed,
                "seed-owned issue type has a cleared workflow; refusing to reattach it",
            )
        if issue_type.workflow_id != workflow.id:
            _conflict(
                workspace,
                seed,
                "seed-owned issue type has a conflicting workflow; refusing to rewire it",
            )
        return issue_type

    if not named_types:
        return IssueType.objects.create(
            workspace_id=workspace.id,
            name=seed["type"],
            is_epic=False,
            is_default=False,
            is_active=True,
            workflow_id=workflow.id,
            external_source=SEED_EXTERNAL_SOURCE,
            external_id=issue_type_external_id,
        )

    issue_type = named_types[0]
    _conflict(
        workspace,
        seed,
        f"active issue type {seed['type']!r} exists without the exact seed marker "
        f"(external ownership: {issue_type.external_source!r}, {issue_type.external_id!r}); "
        "refusing to adopt or rewire it",
    )


def _ensure_transitions(WorkflowTransition, workflow, seed, state_map):
    active_pairs = set(
        WorkflowTransition.objects.filter(
            workflow_id=workflow.id,
            deleted_at__isnull=True,
        ).values_list("from_state_id", "to_state_id")
    )
    for from_name, to_name in seed["transitions"]:
        pair = (state_map[from_name], state_map[to_name])
        if pair not in active_pairs:
            WorkflowTransition.objects.create(
                workflow_id=workflow.id,
                from_state_id=pair[0],
                to_state_id=pair[1],
            )
            active_pairs.add(pair)


def seed_default_workflows(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    IssueType = apps.get_model("db", "IssueType")
    Workflow = apps.get_model("db", "Workflow")
    WorkflowState = apps.get_model("db", "WorkflowState")
    WorkflowTransition = apps.get_model("db", "WorkflowTransition")

    for workspace in Workspace.objects.filter(deleted_at__isnull=True).iterator():
        for seed in WORKFLOW_SEEDS:
            workflow = _get_workflow(Workflow, workspace, seed)
            _get_issue_type(IssueType, workspace, seed, workflow)

            state_map = {}
            for index, (name, group, is_default) in enumerate(seed["states"]):
                state = _get_workflow_state(
                    WorkflowState,
                    workspace,
                    seed,
                    workflow,
                    name,
                    group,
                    is_default,
                    index,
                )
                state_map[name] = state.id

            _ensure_transitions(WorkflowTransition, workflow, seed, state_map)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_workflow_workflowstate_workflowtransition_and_more'),
    ]

    operations = [migrations.RunPython(seed_default_workflows, reverse_code=migrations.RunPython.noop)]
