# Generated by Django 5.2.15 on 2026-09-25 07:03

from django.db import migrations
from django.utils.text import slugify


WORKFLOW_SEEDS = [
    {
        "type": "Incident",
        "workflow": "Incident Workflow",
        "states": [
            ("New", "backlog", True),
            ("In Progress", "started", False),
            ("On Hold", "started", False),
            ("Resolved", "completed", False),
            ("Closed", "completed", False),
        ],
        "transitions": [
            ("New", "In Progress"),
            ("In Progress", "On Hold"),
            ("In Progress", "Resolved"),
            ("On Hold", "In Progress"),
            ("Resolved", "Closed"),
            ("Resolved", "In Progress"),
        ],
    },
    {
        "type": "Problem",
        "workflow": "Problem Workflow",
        "states": [
            ("New", "backlog", True),
            ("Investigating", "started", False),
            ("Known Error", "started", False),
            ("Resolved", "completed", False),
            ("Closed", "completed", False),
        ],
        "transitions": [
            ("New", "Investigating"),
            ("Investigating", "Known Error"),
            ("Investigating", "Resolved"),
            ("Known Error", "Resolved"),
            ("Known Error", "Investigating"),
            ("Resolved", "Closed"),
            ("Resolved", "Investigating"),
        ],
    },
    {
        "type": "Change",
        "workflow": "Change Workflow",
        "states": [
            ("New", "backlog", True),
            ("Assessment", "started", False),
            ("Approval", "started", False),
            ("Implementation", "started", False),
            ("Review", "started", False),
            ("Closed", "completed", False),
        ],
        "transitions": [
            ("New", "Assessment"),
            ("Assessment", "Approval"),
            ("Assessment", "Closed"),
            ("Approval", "Implementation"),
            ("Approval", "Assessment"),
            ("Implementation", "Review"),
            ("Review", "Closed"),
            ("Review", "Implementation"),
        ],
    },
    {
        "type": "Improvement",
        "workflow": "Improvement Workflow",
        "states": [
            ("New", "backlog", True),
            ("In Progress", "started", False),
            ("Done", "completed", False),
        ],
        "transitions": [
            ("New", "In Progress"),
            ("In Progress", "Done"),
            ("In Progress", "New"),
            ("Done", "In Progress"),
        ],
    },
]

GROUP_COLORS = {
    "backlog": "#60646C",
    "unstarted": "#60646C",
    "started": "#F59E0B",
    "completed": "#46A758",
    "cancelled": "#9AA4BC",
}


def seed_default_workflows(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    IssueType = apps.get_model("db", "IssueType")
    Workflow = apps.get_model("db", "Workflow")
    WorkflowState = apps.get_model("db", "WorkflowState")
    WorkflowTransition = apps.get_model("db", "WorkflowTransition")

    for workspace in Workspace.objects.filter(deleted_at__isnull=True).iterator():
        for seed in WORKFLOW_SEEDS:
            issue_type, _ = IssueType.objects.get_or_create(
                workspace_id=workspace.id,
                name=seed["type"],
                deleted_at__isnull=True,
                defaults={"is_epic": False, "is_default": False, "is_active": True},
            )
            workflow, _ = Workflow.objects.get_or_create(
                workspace_id=workspace.id,
                name=seed["workflow"],
                deleted_at__isnull=True,
                defaults={"is_active": True},
            )
            if issue_type.workflow_id != workflow.id:
                issue_type.workflow_id = workflow.id
                issue_type.save(update_fields=["workflow"])

            state_map = {}
            for index, (name, group, is_default) in enumerate(seed["states"]):
                wf_state, _ = WorkflowState.objects.get_or_create(
                    workflow_id=workflow.id,
                    name=name,
                    deleted_at__isnull=True,
                    defaults={
                        "group": group,
                        "color": GROUP_COLORS[group],
                        "slug": slugify(name),
                        "sequence": (index + 1) * 15000,
                        "is_default": is_default,
                    },
                )
                state_map[name] = wf_state.id

            for from_name, to_name in seed["transitions"]:
                WorkflowTransition.objects.get_or_create(
                    workflow_id=workflow.id,
                    from_state_id=state_map[from_name],
                    to_state_id=state_map[to_name],
                    deleted_at__isnull=True,
                )


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_workflow_workflowstate_workflowtransition_and_more'),
    ]

    operations = [migrations.RunPython(seed_default_workflows, reverse_code=migrations.RunPython.noop)]
