# Generated by Django 5.2.15 on 2026-09-28

from django.db import migrations
from django.db.models import Count, Q
from django.utils import timezone
from django.utils.text import slugify


WORKFLOW_SUFFIX = " Workflow"
DEFAULT_STATE_NAME = "New"
DEFAULT_STATE_GROUP = "backlog"
DEFAULT_STATE_COLOR = "#60646C"


def derived_workflow_name(type_name):
    return f"{type_name}{WORKFLOW_SUFFIX}"


def live_workflows(Workflow, workspace_id):
    return Workflow.objects.filter(workspace_id=workspace_id, deleted_at__isnull=True)


def name_is_free(Workflow, workspace_id, name, exclude_id=None):
    query = live_workflows(Workflow, workspace_id).filter(name=name)
    if exclude_id is not None:
        query = query.exclude(id=exclude_id)
    return not query.exists()


def unique_workflow_name(Workflow, workspace_id, base_name):
    if name_is_free(Workflow, workspace_id, base_name):
        return base_name
    index = 2
    while not name_is_free(Workflow, workspace_id, f"{base_name} ({index})"):
        index += 1
    return f"{base_name} ({index})"


def ensure_default_state(WorkflowState, workflow, user_id):
    states = list(
        WorkflowState.objects.filter(workflow_id=workflow.id, deleted_at__isnull=True).order_by("sequence", "id")
    )
    if not states:
        WorkflowState.objects.create(
            workflow_id=workflow.id,
            name=DEFAULT_STATE_NAME,
            group=DEFAULT_STATE_GROUP,
            color=DEFAULT_STATE_COLOR,
            slug=slugify(DEFAULT_STATE_NAME),
            sequence=15000,
            is_default=True,
            created_by_id=user_id,
            updated_by_id=user_id,
        )
        return
    if not any(state.is_default for state in states):
        first = states[0]
        first.is_default = True
        first.save(update_fields=["is_default", "updated_at"])


def adopt_or_create_workflow(Workflow, workspace, issue_type):
    if issue_type.workflow_id:
        workflow = live_workflows(Workflow, workspace.id).filter(id=issue_type.workflow_id).first()
        if workflow is not None:
            return workflow
    target_name = derived_workflow_name(issue_type.name)
    orphan = (
        live_workflows(Workflow, workspace.id)
        .filter(name=target_name)
        .annotate(live_types=Count("issue_types", filter=Q(issue_types__deleted_at__isnull=True)))
        .filter(live_types=0)
        .order_by("created_at", "id")
        .first()
    )
    if orphan is not None:
        return orphan
    return Workflow.objects.create(
        workspace_id=workspace.id,
        name=unique_workflow_name(Workflow, workspace.id, target_name),
        is_active=issue_type.is_active,
        created_by_id=workspace.owner_id,
        updated_by_id=workspace.owner_id,
    )


def clone_workflow(Workflow, WorkflowState, WorkflowTransition, source, workspace, issue_type):
    clone = Workflow.objects.create(
        workspace_id=workspace.id,
        name=unique_workflow_name(Workflow, workspace.id, derived_workflow_name(issue_type.name)),
        description=source.description,
        is_active=issue_type.is_active,
        created_by_id=workspace.owner_id,
        updated_by_id=workspace.owner_id,
    )
    state_map = {}
    for state in WorkflowState.objects.filter(workflow_id=source.id, deleted_at__isnull=True).order_by(
        "sequence", "id"
    ):
        new_state = WorkflowState.objects.create(
            workflow_id=clone.id,
            name=state.name,
            description=state.description,
            color=state.color,
            slug=state.slug,
            sequence=state.sequence,
            group=state.group,
            is_default=state.is_default,
            created_by_id=workspace.owner_id,
            updated_by_id=workspace.owner_id,
        )
        state_map[state.id] = new_state.id
    for transition in WorkflowTransition.objects.filter(workflow_id=source.id, deleted_at__isnull=True):
        if transition.from_state_id in state_map and transition.to_state_id in state_map:
            WorkflowTransition.objects.create(
                workflow_id=clone.id,
                from_state_id=state_map[transition.from_state_id],
                to_state_id=state_map[transition.to_state_id],
                created_by_id=workspace.owner_id,
                updated_by_id=workspace.owner_id,
            )
    return clone, state_map


def repoint_project_mirrors(State, type_id, state_map):
    for old_state_id, new_state_id in state_map.items():
        State.objects.filter(
            type_id=type_id,
            workflow_state_id=old_state_id,
            deleted_at__isnull=True,
        ).update(workflow_state_id=new_state_id, updated_at=timezone.now())


def soft_delete_orphan_workflows(Workflow, WorkflowState, WorkflowTransition, workspace):
    now = timezone.now()
    orphans = (
        live_workflows(Workflow, workspace.id)
        .annotate(live_types=Count("issue_types", filter=Q(issue_types__deleted_at__isnull=True)))
        .filter(live_types=0)
    )
    for workflow in orphans.iterator():
        WorkflowState.objects.filter(workflow_id=workflow.id, deleted_at__isnull=True).update(
            deleted_at=now, updated_at=now
        )
        WorkflowTransition.objects.filter(workflow_id=workflow.id, deleted_at__isnull=True).update(
            deleted_at=now, updated_at=now
        )
        Workflow.objects.filter(id=workflow.id).update(deleted_at=now, updated_at=now)


def normalize_type_workflows(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    IssueType = apps.get_model("db", "IssueType")
    Workflow = apps.get_model("db", "Workflow")
    WorkflowState = apps.get_model("db", "WorkflowState")
    WorkflowTransition = apps.get_model("db", "WorkflowTransition")
    State = apps.get_model("db", "State")

    for workspace in Workspace.objects.filter(deleted_at__isnull=True).iterator():
        issue_types = list(
            IssueType.objects.filter(
                workspace_id=workspace.id, deleted_at__isnull=True, is_epic=False
            ).order_by("created_at", "id")
        )
        # 1. Tiap type non-epic punya workflow (adopsi/ciptakan) + default state.
        for issue_type in issue_types:
            workflow = adopt_or_create_workflow(Workflow, workspace, issue_type)
            if issue_type.workflow_id != workflow.id:
                issue_type.workflow_id = workflow.id
                issue_type.save(update_fields=["workflow_id", "updated_at"])
            ensure_default_state(WorkflowState, workflow, workspace.owner_id)
        # 2. Workflow yang dipakai beberapa type: sisakan untuk type tertua, clone
        #    untuk sisanya + re-point mirror project milik type itu.
        by_workflow = {}
        for issue_type in issue_types:
            by_workflow.setdefault(issue_type.workflow_id, []).append(issue_type)
        for workflow_id, linked_types in by_workflow.items():
            if len(linked_types) < 2:
                continue
            source = live_workflows(Workflow, workspace.id).filter(id=workflow_id).first()
            if source is None:
                continue
            for extra_type in linked_types[1:]:
                clone, state_map = clone_workflow(
                    Workflow, WorkflowState, WorkflowTransition, source, workspace, extra_type
                )
                extra_type.workflow_id = clone.id
                extra_type.save(update_fields=["workflow_id", "updated_at"])
                repoint_project_mirrors(State, extra_type.id, state_map)
        # 3. Rename ke nama derived (hanya bila bebas) + sync is_active.
        for issue_type in issue_types:
            workflow = live_workflows(Workflow, workspace.id).filter(id=issue_type.workflow_id).first()
            if workflow is None:
                continue
            changed = False
            target_name = derived_workflow_name(issue_type.name)
            if workflow.name != target_name and name_is_free(
                Workflow, workspace.id, target_name, exclude_id=workflow.id
            ):
                workflow.name = target_name
                changed = True
            if workflow.is_active != issue_type.is_active:
                workflow.is_active = issue_type.is_active
                changed = True
            if changed:
                workflow.save(update_fields=["name", "is_active", "updated_at"])
        # 4. Orphan yang tersisa di-soft-delete.
        soft_delete_orphan_workflows(Workflow, WorkflowState, WorkflowTransition, workspace)


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0124_seed_default_workflows"),
    ]

    operations = [
        migrations.RunPython(normalize_type_workflows, reverse_code=migrations.RunPython.noop),
    ]
