# Generated by Django 5.2.15 on 2026-10-03

from django.db import migrations, models
from django.db.models import Q
from django.utils.text import slugify


DEFAULT_STATES = [
    {"name": "Backlog", "color": "#60646C", "sequence": 15000, "group": "backlog", "default": True},
    {"name": "Todo", "color": "#60646C", "sequence": 25000, "group": "unstarted", "default": False},
    {"name": "In Progress", "color": "#F59E0B", "sequence": 35000, "group": "started", "default": False},
    {"name": "Done", "color": "#46A758", "sequence": 45000, "group": "completed", "default": False},
    {"name": "Cancelled", "color": "#9AA4BC", "sequence": 55000, "group": "cancelled", "default": False},
    {"name": "Triage", "color": "#4E5355", "sequence": 65000, "group": "triage", "default": False},
]


def _manager(model, name):
    """Pakai manager all_objects bila ada; historical model hanya punya manager polos."""
    return getattr(model, name, None) or model._base_manager


def flatten_project_states(apps, schema_editor):
    """Reset state setiap project ke DEFAULT_STATES dan remap semua referensi."""
    Project = apps.get_model("db", "Project")
    State = apps.get_model("db", "State")
    Issue = apps.get_model("db", "Issue")
    DraftIssue = apps.get_model("db", "DraftIssue")
    IssueVersion = apps.get_model("db", "IssueVersion")

    states = _manager(State, "all_state_objects")
    issues = _manager(Issue, "all_objects")
    drafts = _manager(DraftIssue, "all_objects")
    versions = _manager(IssueVersion, "all_objects")
    projects = _manager(Project, "all_objects")

    for project in projects.all().iterator():
        # Lepas semua referensi dulu supaya hard-delete state tidak ikut CASCADE.
        issues.filter(project_id=project.id).update(state_id=None)
        drafts.filter(project_id=project.id).update(state_id=None)
        versions.filter(project_id=project.id).update(state=None)
        projects.filter(id=project.id).update(default_state_id=None)
        states.filter(project_id=project.id).delete()

        default_state = None
        for spec in DEFAULT_STATES:
            state = states.create(
                project_id=project.id,
                workspace_id=project.workspace_id,
                name=spec["name"],
                color=spec["color"],
                slug=slugify(spec["name"]),
                sequence=spec["sequence"],
                group=spec["group"],
                default=spec["default"],
            )
            if spec["default"]:
                default_state = state

        projects.filter(id=project.id).update(default_state_id=default_state.id)
        issues.filter(project_id=project.id).update(state_id=default_state.id)
        drafts.filter(project_id=project.id).update(state_id=default_state.id)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0125_normalize_type_workflows"),
    ]

    operations = [
        migrations.RunPython(flatten_project_states, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_legacy_name_project_when_deleted_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_name_project_type_when_deleted_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_project_workflow_state_when_deleted_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_default_project_type_when_deleted_at_null",
        ),
        migrations.RemoveField(model_name="state", name="type"),
        migrations.RemoveField(model_name="state", name="workflow_state"),
        migrations.RemoveField(model_name="issuetype", name="workflow"),
        migrations.DeleteModel(name="WorkflowTransition"),
        migrations.DeleteModel(name="WorkflowState"),
        migrations.DeleteModel(name="Workflow"),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=Q(deleted_at__isnull=True),
                fields=("project", "name"),
                name="state_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=Q(default=True, deleted_at__isnull=True),
                fields=("project",),
                name="state_unique_default_project_when_deleted_at_null",
            ),
        ),
    ]
