# Generated by Django 5.2.15 on 2026-10-03

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0126_remove_workflows_and_flatten_states"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_legacy_name_project_when_deleted_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_name_project_type_when_deleted_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_project_workflow_state_when_deleted_at_null",
        ),
        migrations.RemoveConstraint(
            model_name="state",
            name="state_unique_default_project_type_when_deleted_at_null",
        ),
        migrations.RemoveField(model_name="state", name="type"),
        migrations.RemoveField(model_name="state", name="workflow_state"),
        migrations.RemoveField(model_name="issuetype", name="workflow"),
        migrations.DeleteModel(name="WorkflowTransition"),
        migrations.DeleteModel(name="WorkflowState"),
        migrations.DeleteModel(name="Workflow"),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=Q(deleted_at__isnull=True),
                fields=("project", "name"),
                name="state_unique_name_project_when_deleted_at_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="state",
            constraint=models.UniqueConstraint(
                condition=Q(default=True, deleted_at__isnull=True),
                fields=("project",),
                name="state_unique_default_project_when_deleted_at_null",
            ),
        ),
    ]
