# Generated by Django 5.2.15 on 2026-10-04

from django.db import migrations, models
from django.db.models import Q


def backfill_requires_service(apps, schema_editor):
    IssueType = apps.get_model("db", "IssueType")
    IssueType.objects.filter(
        Q(name__iexact="Incident") | Q(name__iexact="Request") | Q(name__iexact="Service Request"),
        deleted_at__isnull=True,
        is_epic=False,
    ).update(requires_service=True)


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0127_remove_workflow_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuetype",
            name="requires_service",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_requires_service, migrations.RunPython.noop),
    ]
