[package]
name = "ai"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
chrono = { workspace = true }
chrono-tz = { workspace = true }
rig = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
